version: "3"

services:

  db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123s123
    ports:
      - 27117:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
