apiVersion: v1
kind: Service
metadata:
  name: green-rain
  namespace: go-todo-sec
spec:
  selector:
    app: green-rain
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31002
