apiVersion: v1
kind: Service
metadata:
  name: go-todo-client
  namespace: go-todo
spec:
  selector:
    app: go-todo-client
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
